from setuptools import setup, find_packages


setup(
    name='semsegbench',
    version='0.1.0',
    # author='Your Name',
    # author_email='your.email@example.com',
    description='A package for benchmarking the robustness of semantic segmentation.',
    long_description=open('README.md').read(),
    long_description_content_type='text/markdown',
    url='https://github.com/shashankskagnihotri/benchmarking_reliability_generalization/tree/main/semantic_segmentation',
    packages=find_packages(),
    install_requires=[
        "cospgd==0.1.3",
        "ftfy==6.2.0",
        "huggingface-hub==0.31.2",
        "matplotlib==3.10.3",
        "mmcv==2.0.0",
        "mmdet==3.3.0",
        "mmengine==0.10.7",
        "numpy==1.26.4",
        "opencv-python==3.4.18.65",
        "openmim==0.3.9",
        "pandas",
        "pillow",
        "PyWavelets==1.8.0",
        "PyYAML==6.0.2",
        "regex==2024.4.28",
        "safetensors==0.5.3",
        "scikit-image==0.24.0",
        "scipy==1.13.0",
        "timm==1.0.3",
        "torch==2.0.0+cu118",
        "torchaudio==2.0.1+cu118",
        "torchvision==0.15.1+cu118",
        "tqdm==4.65.2",
        "triton==2.0.0",
    ],
    python_requires='>=3.10, <3.11',
    license='MIT',
)